---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    gateway.networking.k8s.io/generator: ingress2gateway-0.4.0
  name: recipe-ui-ingress-recipe-ui-local
  namespace: recipe-ui
spec:
  hostnames:
    - recipe-ui.local
    - sous-chef-proxy.local
  parentRefs:
    - name: kong
      namespace: kong
  rules:
    - backendRefs:
        - name: recipe-ui-service
          port: 3000
      matches:
        - path:
            type: PathPrefix
            value: /api/v1/recipe-ui
status:
  parents: []
